name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main  # Changed from 'v4' to 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Ensure public directory exists
        run: mkdir -p public  # Ensures the public/ folder exists
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}  # Corrected reference
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy  # Updated step ID
        uses: actions/deploy-pages@v4
